# Generated by Django 5.1.6 on 2026-02-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=12)),
                ('lastName', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
